[tool.ruff]
exclude = [
    ".git",
    "docs",
    "setup.py",
]
line-length = 79
lint.ignore = []
lint.select = [
    "E",
    "F",
    "W",
    "A",
    "ERA",
    "NPY",
    "COM",
    "I002",
    "TID252",
    "FIX",
]

