[tool.ruff]
exclude = [
    ".git",
    "docs",
    "setup.py",
    "pyfar/dsp/filter/_audiofilter.py",
    "pyfar/samplings/external",
]
line-length = 79
lint.ignore = [
    "D200", # One-line docstring should fit on one line with quotes
    "D202", # No blank lines allowed after function docstring
    "D205", # 1 blank line required between summary line and description
    "D401", # First line should be in imperative mood
    "D404", # First word of the docstring should not be "This"
    "B006",
    "B008",
    "PT018", # Assertion should be broken down into multiple parts
    "PT019", # Fixture `_` without value is injected as parameter
]
lint.select = [
    "B",
    "ARG",
    "C4",
    "E",
    "F",
    "W",
    "D",
    "D417",   # Missing argument descriptions in the docstring
    "PT", # Pytest style
    "A",
    "ERA",
    "NPY",
    "COM",
    "I002",
    "TID252",
    "FIX",
]

# Ignore missing docstrings in tests
[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "D100",
    "D101",
    "D103",
    "D104",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
