[tool.ruff]
exclude = [
    ".git",
    "docs",
    "setup.py",
]
line-length = 79
lint.ignore = []
lint.select = [
    "E",
    "F",
    "W",
    "D", # Docstrings
]

# Ignore missing docstrings in tests
[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "D100",
    "D101",
    "D103",
    "D104",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
