on:
  push:
    branches:
      - master
      - develop
      - cookiecutter_create_issue
name: Open new issue

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo pyfar/cookiecutter-pypackage \
            create --title "Issue title" --body "Issue body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
