name: PR Check Label for version Label

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for version label
        run: |
          LABELS_JSON=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/labels)
          VERSION_LABEL=$(echo "$LABELS_JSON" | jq -r '.[].name' | grep -P 'v\d+\.\d+\.\d+' || true)
          if [ -z "$VERSION_LABEL" ]; then
            echo "Error: No version label found on this pull request. Please add a label in the format vX.Y.Z."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
